package id.co.indocyber;

import javax.swing.JOptionPane;

public class TebakAngkaWindow extends javax.swing.JFrame {

    /**
     * Creates new form TebakAngkaWindow
     */
    public TebakAngkaWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconAppLabel = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        petunjukLabel = new javax.swing.JLabel();
        inputAngkaTextField = new javax.swing.JTextField();
        checkAngkaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iconAppLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\icon\\tebakAngkaicon.png")); // NOI18N

        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        petunjukLabel.setText("Klik Tombol Mulai");

        inputAngkaTextField.setEditable(false);
        inputAngkaTextField.setEnabled(false);

        checkAngkaButton.setText("Are You Sure ?!");
        checkAngkaButton.setEnabled(false);
        checkAngkaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAngkaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAngkaTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(iconAppLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(mulaiButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(checkAngkaButton))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(petunjukLabel)))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconAppLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mulaiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(petunjukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAngkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkAngkaButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        angkaSoal = generateAngka();
        petunjukLabel.setText("Masukkan Angka antara 1 - 100");
        inputAngkaTextField.setEditable(true);
        inputAngkaTextField.setEnabled(true);
        mulaiButton.setEnabled(false);
        checkAngkaButton.setEnabled(true);
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void checkAngkaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAngkaButtonActionPerformed

        try {
            String tebakanString = inputAngkaTextField.getText(); //logic yang berpotensi error dimasukkan disini biar kalo ada error di catch dibawah
            int tebakan = Integer.parseInt(tebakanString);
            if (tebakan == angkaSoal) {
                petunjukLabel.setText("Briliant");
                inputAngkaTextField.setEnabled(false);
                mulaiButton.setEnabled(true);
                checkAngkaButton.setEnabled(false);

            } else {
                String message;
                if (tebakan < angkaSoal) {
                    message = "Angka anda lebih kecil";
                } else {
                    message = "Angka anda lebih besar";
                }
                petunjukLabel.setText(message);
            }
        } catch (Exception e) {
            //petunjukLabel.setText("hanya masukkan angka saja"); // disini menangkap masalah
            JOptionPane.showMessageDialog(rootPane, "Hanya Masukkan Angka Saja");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_checkAngkaButtonActionPerformed

    int angkaSoal;

    private int generateAngka() {
        double random = Math.random() * 100;
        double ceilValue = Math.ceil(random);
        int generatedAngkaSoal = (int) ceilValue;
        return generatedAngkaSoal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakAngkaWindow().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAngkaButton;
    private javax.swing.JLabel iconAppLabel;
    private javax.swing.JTextField inputAngkaTextField;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JLabel petunjukLabel;
    // End of variables declaration//GEN-END:variables
}
